### ISSUE TITLE
number of nodes

### ISSUE THREAD

**Issue by zhu-xiaoting** [nkahmed/PGD#10]
Hi there! I tried to apply the method to the CiteSeer dataset with edgelist.txt as input. The input has 3312 nodes, but the --macro returned 3264 nodes. There's no isolated node in the dataset. The number of edges didn't match either. Has anyone met this problem?

**Comment by zhuxt001** [comment]
Hi there! I tried to apply the method to the CiteSeer dataset with edgelist.txt as input. The input has 3312 nodes, but the --macro returned 3264 nodes. There's no isolated node in the dataset. The number of edges didn't match either. Has anyone met this problem?

**Comment by zhu-xiaoting** [comment]
Remove self-loops and then remove isolated nodes.
