### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by danielmawhirter** [nkahmed/pgd#2]
When running make, I get the following output

> g++ -O3  -fopenmp -ffast-math -funroll-loops -fno-strict-aliasing -fomit-frame-pointer -fexpensive-optimizations -funroll-loops -fmove-loop-invariants -fprefetch-loop-arrays -ftree-loop-optimize -ftree-vect-loop-version -ftree-vectorize -o pgd graphlet_driver.o graphlet_utils.cpp graphlet_core.cpp graphlet_rand.cpp
graphlet_driver.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [pgd] Error 1

Is this an issue with my environment's setup or with the build process? I got the same error on two machines.
Thanks

**Comment by nkahmed** [comment]
What is your gcc version?

**Comment by danielmawhirter** [comment]
4.8.4
`make all` works successfully, so I would humbly suggest that the documentation reflect that. Thank you for your quick reply

**Comment by nkahmed** [comment]
Thanks for the feedback!

On Fri, Mar 25, 2016 at 12:26 PM, Daniel Mawhirter <notifications@github.com
> wrote:

> 4.8.4
> make all works successfully, so I would humbly suggest that the
> documentation reflect that. Thank you for your quick reply
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/nkahmed/pgd/issues/2#issuecomment-201442083>
>



-- 
All the best,

Nesreen
