### ISSUE TITLE
input file format csv or mtx

### ISSUE THREAD

**Issue by abitofalchemy** [nkahmed/PGD#3]
Thank you for making your code public. I want to use this for comparing two networks. If I take a small, well studied graph: karate club; changing the edge-list to .mtx and then giving that as input to pgd isn't working. Here is what I do:

1. I changed the KC edge-list file to mtx as so:

```
%% Karate Club Graph (graph is undirected, each edge is saved twice)
%% Nodes: 34 Edges:78*2=156
34 34 78
0 1
0 2
<snip>
```

Then I tried to do: `/pgd -f kc.mtx`

On the other hand, if I change the original edgelist file  by removing the comments and replace them with a header line: `src,dst` it seems to work, so the whole thing on MatrixMarket input file format is confusing, but I'm sure I'm missing part of the big-picture.

**Comment by nkahmed** [comment]
That is not a valid mtx file, so simply change the ".mtx" file extension to anything else (e.g., ".edges") and it will work correctly. There is no need to store the edges twice, though it will still work correctly (just takes slightly longer to read).

Hope this helps!
